#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0b5 on Wed Jan 16 01:35:44 2019
#

import wx
import wx.adv
import main
from pynput.keyboard import Key, Controller

keyboard = Controller()
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((300, 225))
        self.button_1 = wx.Button(self, wx.ID_ANY, "\nSTART\n")
        self.feedbacklink = wx.adv.HyperlinkCtrl(self, wx.ID_ANY, "feedback", "https://docs.google.com/forms/d/e/1FAIpQLScXiqaEHIAT-3eRKe71gvcLnqgseZX44hY8mRy0VYIKjjLtTQ/viewform?vc=0&c=0&w=1&usp=mail_form_link")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.start_p, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(u"පන්හිද-tyiping")
        self.SetBackgroundColour(wx.Colour(216, 191, 216))
        self.button_1.SetMinSize((282, 80))
        self.button_1.SetBackgroundColour(wx.Colour(0, 255, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.button_1, 0, 0, 0)
        feedback = wx.StaticText(self, wx.ID_ANY, u"\nsimple sinhala typing tool\nපන්හිද-tyiping.beta\nfor stop පන්හිද-tyiping press Esc\n")
        feedback.SetFocus()
        sizer_1.Add(feedback, 0, 0, 0)
        sizer_1.Add(self.feedbacklink, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade


    def start_p(self, event):  # wxGlade: panhidha.<event_handler>
        self.end_p(event)
        main.panhidha()
        event.Skip()

    def end_p(self, event):  # wxGlade: panhidha.<event_handler>
        keyboard.press(Key.esc)
        keyboard.release(Key.esc)
        event.Skip()


# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
